# Generated by Django 4.2.4 on 2023-09-26 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=600)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='componentes')),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100, null=True)),
                ('red_social', models.CharField(max_length=20, null=True)),
                ('numero', models.IntegerField()),
                ('domicilio', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('altura', models.IntegerField()),
                ('codigoPostal', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
